{% set version = "0.2.13" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rcppcctz
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/RcppCCTZ_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RcppCCTZ/RcppCCTZ_{{ version }}.tar.gz
  sha256: f4101435ed32b61110fb8e2429da80ea72bce774156075c823743904a4f2abf2

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ stdlib("c") }}
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-rcpp                       # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp >=0.11.0
  run:
    - r-base
    - r-rcpp >=0.11.0

test:
  commands:
    - $R -e "library('RcppCCTZ')"           # [not win]
    - "\"%R%\" -e \"library('RcppCCTZ')\""  # [win]

about:
  home: https://github.com/eddelbuettel/rcppcctz, https://dirk.eddelbuettel.com/code/rcpp.cctz.html
  license: GPL-2.0-or-later
  summary: '''Rcpp'' Access to the ''CCTZ'' timezone library is provided. ''CCTZ'' is a C++ library for translating between absolute and civil times using the rules of a time zone. The ''CCTZ'' source code, released under the Apache 2.0 License, is included in this package. See <https://github.com/google/cctz> for more details.'
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'
    - CCTZ_LICENSE.txt

extra:
  recipe-maintainers:
    - ihnorton
    - shelnutt2
    - conda-forge/r
    - jdblischak
